# Generated by Django 4.1.4 on 2022-12-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Surname')),
                ('username', models.CharField(default='', max_length=50, verbose_name='Username')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Email')),
                ('password', models.TextField(default='', verbose_name='Password')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_to', models.IntegerField(verbose_name='Id to')),
                ('text', models.TextField(verbose_name='Message')),
                ('time', models.DateTimeField(default=0, verbose_name='Time')),
                ('id_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='api.users')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_to', models.IntegerField(verbose_name='Id to')),
                ('id_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='api.users')),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
            },
        ),
    ]
