# Generated by Django 4.1.4 on 2022-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('registration_time', models.DateTimeField(verbose_name='Registration time')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('password', models.CharField(max_length=16, verbose_name='Password')),
            ],
        ),
    ]
