# Generated by Django 4.1.4 on 2022-12-18 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_users_options_users_surname_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration time'),
        ),
    ]
