# Generated by Django 4.1.4 on 2022-12-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_users_registration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='registration_time',
        ),
    ]
